### ISSUE TITLE
Add this repository to packagist.

### ISSUE THREAD

**Issue by rakibabu** [Paazl/magento2-checkout-widget#1]
Hi Paazl,

Can you add this repository to packagist?

**Comment by Frank-Magmodules** [comment]
Hi @rakibabu  yes it will, but Paazl first needs to resolve an issue with the namespace at Packagist. Once done, the package will be available on Packagist

For now you can add the GitHub Repo, see the .Readme and:
`composer config repositories.paazl-magento2-checkout-widget vcs git@github.com:paazl/magento2-checkout-widget.git`

**Comment by rakibabu** [comment]
thanks :)

**Comment by Marvin-Magmodules** [comment]
Package is available: https://packagist.org/packages/paazl/magento2-checkout-widget
