### ISSUE TITLE
Backend issue PHP 8.3 on retry

### ISSUE THREAD

**Issue by denniselgentos** [Paazl/magento2-checkout-widget#109]
When clicking on "Retry" in the backend at "Shipping & Handling Information" on the order we get an error "Error sending order data to Paazl: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated". Model/Api/Builder/Order.php#L190

See:
https://github.com/Paazl/magento2-checkout-widget/blob/master/Model/Api/Builder/Order.php#L190

PHP: 8.3

**Comment by Frank-Magmodules** [comment]
Thank you for informing @denniselgentos! We're in the final stages of preparing our release, which addresses the issue you mentioned. It should be launching very soon. I'll keep you updated on our progress.

**Comment by Frank-Magmodules** [comment]
Hi @denniselgentos, I'm happy to share that this has been addressed in the [latest release](https://github.com/Paazl/magento2-checkout-widget/releases)! I'm closing this issue for now, but please feel free to respond or reopen the ticket if needed.
