### ISSUE TITLE
Wrong Paazl API response

### ISSUE THREAD

**Issue by RomanMoshchytskiy** [Paazl/magento2-checkout-widget#112]
HI,

We are having problems with the request "https://api.paazl.com/v1/checkout/?reference=" - for some quotes and then for the orders themselves, the response to the request is empty (not quite empty, but with null instead of values). 
Example from `mm_paazl_order` table:
```composer log
{"type":null,"identifier":null,"price":0,"option_title":null,"preferred_delivery_date":null,"estimated_delivery_range":null,"carrier_pickup_date":null}
```
So if during checkout Paazl API doesn't return normal response with identifier and delivery type then order can't update "Paazl order status" and because of that we can't send shipment using SAP system.

![Screenshot from 2024-08-06 12-40-01](https://github.com/user-attachments/assets/e17cbf3c-818c-403b-8eb6-477e6ee2a56a)
![Screenshot from 2024-08-06 13-00-27](https://github.com/user-attachments/assets/007c0d20-f41c-49fe-97d3-85a2ba9ccb27)

No other information was provided because it was confidential. It was provided during a conversation with Paazl support.

We already discussed this with Paazl support but they told us to create a ticket on github.

Magento version
2.4.5-p7

Plugin version
1.16.1

**Comment by Frank-Magmodules** [comment]
Hi @RomanMoshchytskiy,

Thank you for raising the issue. Based on the information provided, we’re unable to reproduce the problem. Are you using a headless setup? If possible, could you [share](https://www.magmodules.eu/help#:~:text=Support%20by%20e,contact%40magmodules.eu) temporary development/staging details with us so we can investigate this issue further with you?

Thanks!

**Comment by RomanMoshchytskiy** [comment]
We do not use a headless setup.
Here is the staging URL: https://wwwstaging.123optic.com/
This problem mostly occurs with not logged customers.

**Comment by Frank-Magmodules** [comment]
Hi @RomanMoshchytskiy, could you please reach out to us directly so we can securely share more details? :)  
Thanks!

**Comment by Frank-Magmodules** [comment]
@RomanMoshchytskiy, please provide the backend and SSH details, along with the exact steps to reproduce the issue, including the expected and actual results in the staging/development environment where we can replicate this.

**Comment by RomanMoshchytskiy** [comment]
Can you share your ssh key?

**Comment by Frank-Magmodules** [comment]
Just reach out to us; it's better to handle all these questions and details via email.

**Comment by RomanMoshchytskiy** [comment]
Oh, I thought if I emailed back it wouldn't show up on the ticket
