### ISSUE TITLE
checkout stuck for customers without address

### ISSUE THREAD

**Issue by mveldhuizen** [Paazl/magento2-checkout-widget#113]
During checkout some customers can not check out their order. Proceed to checkout step 2 is not working.
This bug is happening since release 1.17.1.

During debugging I can see the following error:
TypeError: Cannot read properties of undefined (reading 'country_id')

See also:
![Scherm­afbeelding 2024-08-28 om 14 08 50](https://github.com/user-attachments/assets/8936672f-f760-4c27-8291-4f66ff101d82)

After some research I have concluded there is an issue when the customer does not have an address saved in their account. We then get the normal guest checkout form but than this issue happens. 

Customers with an address works fine. And when creating a new address during checkout this issue also is no problem.

I have tested the following solution and this seems to work, but i'm not sure if there are any use cases that I might have missed:

vendor/paazl/magento2-checkout-widget/view/frontend/web/js/checkout/action/set-shipping-information-mixin.js:58
Change:
`if (isCustomerLogin) {`

To:
`if (isCustomerLogin && getAddressId() !== null) {`

**Comment by Frank-Magmodules** [comment]
Hi @mveldhuizen, thank you for reporting this issue. I’m pleased to inform you that we’ve just released a [new version](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.17.2) of the plugin that addresses this problem. I’ll go ahead and close this issue for now, but please feel free to reopen it if needed.
