### ISSUE TITLE
Customers quotes tokens invalid after 30 days

### ISSUE THREAD

**Issue by rakibabu** [Paazl/magento2-checkout-widget#14]
Hi Paazl,

When a customer is logged in, after 30 days (Model/TokenRetriever.php:121) the token in mm_paazl_quote is expired. So the customer can't select any shipping method. 

Possible solutions:
1. Make a purge cronjob to remove them from the mm_paazl_quote table to get a new token from your api.
2. Check the date in Model/TokenRetriever.php:95. When expired retrieve a new token.

Can you please fix this?

**Comment by Marvin-Magmodules** [comment]
Thank you for the detailed error report, issue has been resolved in [v1.1.0](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.1.0). Closing this issue now, but feel free to reopen is the issues still occurs
