### ISSUE TITLE
Issue after updating 2.3.3

### ISSUE THREAD

**Issue by wahidnory** [Paazl/magento2-checkout-widget#16]
Hey,

Yesterday we updated a magento 2 store to version 2.3.3. and with it paazl module as well.

But to our surprise we received an error message (in the magento backend) on Content > Pages and Sales > Invoices.
For Content > Pages: "Not registered handle cms_page_listing_data_source".
For Sales > Invoices: "No registered handle sales_order_invoice_grid_data_source".

After downgrading paazl to a lower version the error was gone.

Hopefully this is clear enough for you guys to be able to fix, or reproduce the issue.

Cheers and thank you in advance.

**Comment by Frank-Magmodules** [comment]
Hi @wahidnory ,

Thank you for your report, we will look at this immediately and keep you informed about a solution.

**Comment by Frank-Magmodules** [comment]
Hi @wahidnory ,

The issue has been resolved and merged into [v1.1.1 ](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.1.1)release. Thanks again and sorry for the circumstances. Closing this issue now. Feel free to reopen the issue if this still occurs.
