### ISSUE TITLE
Compilation error in Magento 2.2.5

### ISSUE THREAD

**Issue by visualwebs** [Paazl/magento2-checkout-widget#18]
When I compile the system I receive and error in that class

Paazl\CheckoutWidget\Controller\Adminhtml\Order\Data\Send

HttpPostActionInterface doesn´t exists.  So this Class doesn´t exist in Magento 2.2.5 and you need to edit this controller if you want to make compatible.

Remove the "implements HttpPostActionInterface" does the trick to me.

**Comment by Marvin-Magmodules** [comment]
Thank you for the detailed error report, we have issued a new release with a fix; [v1.1.2](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.1.2). Closing this issue now, but feel free to reopen is the issues still occurs
