### ISSUE TITLE
number_format returns string not a double value.

### ISSUE THREAD

**Issue by rakibabu** [Paazl/magento2-checkout-widget#2]
Hi Paazl,

In `vendor/paazl/magento2-checkout-widget/Model/Checkout/WidgetConfigProvider.php` on `line 189` the method formatPrice is returning a string when formatting with the default values of number_format. Any order above 1000 wil have a comma in the price wich is not accepted by your API.

Can you fix this with with this? 

```
public function formatPrice($price)
{
        return number_format($price, 2, ',', '');
}
```

Please merge: https://github.com/Paazl/magento2-checkout-widget/pull/3

**Comment by Marvin-Magmodules** [comment]
Hi @rakibabu, thank you for the detailed error report and the PR! I've just pushed our own fix, as the suggested edit and PR uses a comma as decimal point. Fix is merged into the [1.0.6](https://github.com/Paazl/magento2-checkout-widget/tree/1.0.6) branch that will be released this week.

**Comment by Marvin-Magmodules** [comment]
Merged into master. Closing this issue now, but please feel free to reopen the issue if this problem still occurs.

**Comment by rakibabu** [comment]
Thanks Marvin :)
