### ISSUE TITLE
problems with address of pickup locations 

### ISSUE THREAD

**Issue by melnickforever** [Paazl/magento2-checkout-widget#33]
Address of pickup locations not sets like shipping address.

**Comment by Frank-Magmodules** [comment]
Hi @samgranger  , thanks for opening this issue. 
This issue has been resolved in the [V 1.2.0](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.2.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
