### ISSUE TITLE
Compatibility issues with other third party modules that extend the shippingAdditional section of the checkout_index_index.xml

### ISSUE THREAD

**Issue by duckchip** [Paazl/magento2-checkout-widget#34]
Hi All,

We noticed when installing this module, functionality of other third party modules got broken. To be more precise, the shippingAdditional section shows flaws. 

Magento documentation also states that layout processors should be used when adding custom things in the checkout https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_custom_checkbox.html

### Preconditions (*)
1. Magento 2.3.3
2. paazl/magento2-checkout-widget 1.1.4  

### Steps to reproduce (*)

1. Create a module that adds data to the ShippingAdditional with a layout Processor
2. Install The Paazl module

### Expected result (*)
2. Both the Paazl and custom module should have their children in the shippingAdditional section

### Actual result (*)
2. No children are rendered

The trick is to change the implementation to a layout processor.

**Comment by Frank-Magmodules** [comment]
@duckchip , Thank you for opening this issue, we will investigate this issue and your PR so we can implement this in our upcoming release! Thanks again!

**Comment by Frank-Magmodules** [comment]
Hi @samgranger  , thanks again for opening this issue. 
This issue has been resolved in the [V 1.2.0](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.2.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
