### ISSUE TITLE
Wrong shipping address info delivered to Paazl

### ISSUE THREAD

**Issue by visualwebs** [Paazl/magento2-checkout-widget#41]
I want to report a possible bug, using version 1.2.1

We have a single order with 2 different addresses.
For shipping address the customer fills company "A" and "street A".
For billing address the customer fills "street B" and leaves company empty.
The order comes from guest customer and the issue looks random, in staging I can´t reproduce.

The result in Paazl panel after push the order is shipping address: company "A" and "Street B".
Something looks wrong when delivering data with different shipping/billing address

**Comment by Frank-Magmodules** [comment]
Hi @visualwebs ,

Thank you for opening this issue. Strange, I'm not able to reproduce this as well. I keep getting just the shipping details.  Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange;

- Paazl Logfile from /var/log/Paazl.log
- Order Details
- Magento Back-end details (To see checkout settings)

So we can help you out with this. Please share if you can find a pattern in this issue or the exact steps on how to reproduce this issue if successful, the more information the better.
Thanks,

Frank
