### ISSUE TITLE
ver.1.2.2 errors during bin/magento se:di:co

### ISSUE THREAD

**Issue by demtaric** [Paazl/magento2-checkout-widget#43]
After upgrade of the module
After running `bin/magento se:di:co` it will fails with message:

> Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in vendor/paazl/magento2-checkout-widget/Model/Api/Builder/OrderTest.php on line 19

Problem there that namespace in that file is not correct, but I would say that file itself placed in wrong place.
According to Magento standarts all Unit test should be placed under "Test\Unit" directory.

**Comment by Frank-Magmodules** [comment]
Hi @demtaric, thanks for opening this issue.
This issue has been resolved in the [v1.2.3](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.2.3) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
