### ISSUE TITLE
Packagist 1.6.0 release

### ISSUE THREAD

**Issue by ericclaeren** [Paazl/magento2-checkout-widget#59]
Hi, 

There's currently no 1.6.0 release on packagist
https://packagist.org/packages/paazl/magento2-checkout-widget

Couldn't install the latest until I added the repository in my composer.json to use directly from source.

Wanted to let you know, cheers.

**Comment by Marvin-Magmodules** [comment]
Hi @ericclaeren, thank you for opening the issue, looks like something is wrong with the connection to Packagist. Just added the [1.6.0](https://packagist.org/packages/paazl/magento2-checkout-widget#1.6.0) version manually, and will look into this issue on the next release!

**Comment by Frank-Magmodules** [comment]
Hi @ericclaeren, this seems to be fixed. 
We are closing this issue now but please feel free to reopen the issue if this still occurs.
