### ISSUE TITLE
Incorrect total price for shipping calculation

### ISSUE THREAD

**Issue by ericclaeren** [Paazl/magento2-checkout-widget#66]
Hi,

We have noticed that the incorrect total price amount is being used to fetch shipping methods.
I'm guessing this part is responsible for the api call for shipping methods and determining which methods are available.

In \Paazl\CheckoutWidget\Model\Checkout\WidgetConfigProvider::getConfig
```
"shipmentParameters"         => [
      "totalWeight"   => (float)$this->getTotalWeight(),
      "totalPrice"    => (float)$this->getQuote()->getSubtotalWithDiscount(),
      "numberOfGoods" => (int)$this->getProductsCount(),
      "goods"         => $goods
  ],
```

The total price is based on getSubtotalWithDiscount() but this calculates an incorrect amount.

In our case our Tax/Discount settings are as following, all prices are including tax.
![image](https://user-images.githubusercontent.com/4748495/123227814-3ce9a600-d4d5-11eb-8435-8ed3b811ddd5.png)

### An example:

These are the magento totals data from the checkout. With a 45% discount applied.
![image](https://user-images.githubusercontent.com/4748495/123228166-9225b780-d4d5-11eb-8f09-72aa58b8e73e.png)

Product price including tax is 34.95 * 3 qty = **104.85**
This makes the total including tax 104.85 - 45% (47.18) = **57.67**
The grand total excluding tax is is: **47.65**

Where it goes wrong is that subtotal is the amount excluding tax and Magento adds the discount amount.
104.85 / 1.21 = 86.65 ->Magento apparently rounds this to **86.64**.

So getSubtotalWithDiscount() equals to 86.64 + -47.18 = **39.46**

The discount added to the subtotal is **including tax!** So this amount is incorrect, the real subtotal + discount should be.
86.64. + -(47.18 / 1.21) = **47.65** And this matches the grand total ex tax.

This issue leaves us with frustrated customers, because they think the have the right for free shipping when reviewing their total amount in the cart, but then get to pay shipping costs.

### The solution?

Use grand total or make sure the two scenario's for including or excluding tax in discount applies for the total price sent to Paazl or if the costs for shipping are to different per store, make it an configurable option. So you could set the logic for the total price in the paazl module.

Total price for shipping costs: 
- Grand total including TAX
- Grand total excluding TAX
- Subtotal including DISCOUNT

Cheers, Eric

**Comment by paazl-jaime** [comment]
hi @ericclaeren ,

If you'd like, you can check out the implementation of the shipping costs calculation here.

https://github.com/Paazl/magento2-checkout-widget/tree/1.8.0

**Comment by ericclaeren** [comment]
Hi @paazl-jaime 

Thanks, could you point me to the code that was changed or which setting has changed for this feature?

Cheers, Eric

**Comment by paazl-jaime** [comment]
Hi @ericclaeren ,

Yes, definitely. You can find the setting in the Paazl settings in the extension. Use the dropdown field _Advanced Settings > Total Price._

- Subtotal including DISCOUNT
- Grand total

**Comment by johanst1409** [comment]
Hi @paazl-jaime,

I've taken over from @ericclaeren for this issue.
It all seems to work correctly now, do you have an idea when this will be officially released?

Cheers,
Johan

**Comment by ericclaeren** [comment]
Hi @paazl-jaime 

It all seems to work, but we ran into a second issue, after switching to grant total, the current amount in paazl doesn't match up. Because the amount in the shipping matrix is entered without tax, when switching to an amount with tax. This might bring some problems when switching and seamless deploying this code would be very difficult.

Current situation.

_Free shipping at 50,- inc tax_

**Without discount**
Tax: 21%
Amount in cart 50.00 inc tax

subtotal: 41.32
subtotal_with_discount: 41.32
grand_total: 50

Currently set 2 matrices first max amount 41.31 with shipping price of 5.00 second no max and shipping price of 0.00.

Default setting in Magento (subtotal_inc_discount) this would give you free shipping when set to 41.31.
Setting Grand Total in Magento (grand_total) would give you free shipping: 41.31, but the setting does not match the matrices in paazl and may be confusing for customers.

**With discount of __25%__**
Tax: 21%
Amount in cart 50.00 inc tax

discount: 30% (inc tax): 15.00
subtotal: 41.32
subtotal_with_discount: 26.32 (41.32 + -15.00)
grand_total: 35.00

Default setting in Magento (subtotal_inc_discount) would not give you free shipping. Because this would not go over the max amount of 41.31, this our current issue.
Setting Grand Total in Magento (grand_total) Wouldn't give you free shipping, because the grand total is also below the amount of 41.31

So revising my first solution to take the grand_total was probably wrong. This is confusing and won't work in more scenarios.

The better option would be to set these options.

subtotal
subtotal_with_discount (but take inc/exc discount into account) This value is only applicable when the discount is set ex tax

But the question is also, what are clients supposed to enter in the shipping matrix is it normally used inc or ex taxes? Maybe this has to become clear for the user to match the settings in paazl and magento.

Cheers, Eric

**Comment by paazl-jaime** [comment]
Hi @ericclaeren ,

Apologies for the delay. It appears I didn't receive any notification for your message. Many thanks for the elaborate explanation.

To answer your question, the grand_total option could be used to push the total order value to Paazl including VAT. This is fine for the Paazl Delivery Matrix, which is VAT-naive. We have (non-Magento) customers who place all prices in their matrix as **including VAT**. Using the Grand Total would give Magento merchants the same option.

From a pragmatic perspective, would the following settings resolve your issues?

- subtotal
- subtotal_with_discount
- grand_total

I also included the grand_total option. It might even be an option for your client to switch to using incl VAT prices in the Delivery Matrix. It might mirror the actual consumer logic in a more accurate way. But of course, that's always up to our clients.

**Comment by ericclaeren** [comment]
Hi @paazl-jaime 

No worries, those values/settings would be sufficient, currently I've added an after plugin to set the value to subtotal. This is running on production and has proven to work for us.

Thanks, Eric

**Comment by Frank-Magmodules** [comment]
HI @ericclaeren ,

<table><tbody><tr><td>We are happy to share that we've just released the new <a href="https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.8.0">1.8.0</a> version with a fix for this issue. Thank you again for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.</td></tr></tbody></table>

Have a good weekend ahead!
