### ISSUE TITLE
Canceling an order in M2 backend causes paazl module to crash on afterSave Plugin call

### ISSUE THREAD

**Issue by ThijsdejongSNC** [Paazl/magento2-checkout-widget#67]
M2 version: 2.4.3
Paazl Module version "1.7.0"

Steps to reproduce: create a new order in front-end, with paazl link. Cancel order in backend.

`TypeError: Argument 2 passed to Paazl\CheckoutWidget\Plugin\Sales\OrderRepositoryPlugin::afterSave() must implement interface Magento\Sales\Api\Data\OrderInterface, null given, called in /httpdocs/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /httpdocs/vendor/paazl/magento2-checkout-widget/Plugin/Sales/OrderRepositoryPlugin.php:91
Stack trace:
#0 //vendor/magento/framework/Interception/Interceptor.php(146): Paazl\CheckoutWidget\Plugin\Sales\OrderRepositoryPlugin->afterSave()`

**Comment by Frank-Magmodules** [comment]
HI @ThijsdejongSNC ,  
  
Thank you for opening this issue, I can't reproduce this in our demo environment directly so we need some more time to investigate this issue. Will share the outcome on this asap.

**Comment by Frank-Magmodules** [comment]
Hi @ThijsdejongSNC ,

Seems we can't reproduce this issue from our side, can you please fill in our \[support form\](https://www.magmodules.eu/support-form.html) with (preferably staging/development) details of the environment so we can take a look with you on this issue?

Thanks!

**Comment by ThijsdejongSNC** [comment]
Our bad, this was a problem in another plugin from our side. please close.
