### ISSUE TITLE
Do not load css via js widget

### ISSUE THREAD

**Issue by rakibabu** [Paazl/magento2-checkout-widget#7]
Hi Paazl,

Can you remove the external css load for https://widget-acc.paazl.com/v1/checkout.js. We've to override a lot of styling to accomplice a simple thing. 

Can you include it in the head in the xml so we can have more control over the css?

Thanks in advance.

**Comment by Paazl** [comment]
Hi Raki,
Unfortunately the external load is mandatory for the full functioning of the Paazl Checkout widget.
This won't be changed for now.

Thanks for your feedback!
