### ISSUE TITLE
Wrong usage of infotext

### ISSUE THREAD

**Issue by LexKoomen** [Paazl/magento2-checkout-widget#70]
I'm not sure where the infotext is for right now but it's unusable for now.

There is no default value for infotext, and also no admin field to fill anything in.
Therefore Paazl\CheckoutWidget\Plugin\Carrier\Infotext plugin is useless

What is the reason for this functionality?

**Comment by Marvin-Magmodules** [comment]
Hi Lex, thank you for opening this issue, this was indeed missing. Admin option + frontend implementation has been added in [v1.9.0](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.9.0) to show some information message above the shipping option. We are closing this issue now but please feel free to reopen the issue if this still occurs.
