### ISSUE TITLE
1.8.0 or 1.9.0 seem to break checkout in Magento 2.4.3

### ISSUE THREAD

**Issue by ericclaeren** [Paazl/magento2-checkout-widget#74]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'totals')
    at Object.<anonymous> (set-shipping-information-mixin.js:31)
```
![image](https://user-images.githubusercontent.com/4748495/136228614-6ed0bfb8-af0b-4913-916f-8cf0bc4c5f6e.png)

[Diff](https://github.com/Paazl/magento2-checkout-widget/compare/1.7.0...1.9.0#diff-fb1562bba8edc521c1cbaa059f61060740d57485d2cce30a63d5656131ae5228L31)

Cheers, Eric

**Comment by Frank-Magmodules** [comment]
HI @ericclaeren  ,

We are happy to share that we've just released the new \[1.9.3 version\](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.9.3) with a fix for this issue.  
Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
