### ISSUE TITLE
ProductData for bundle products sends the total bundle price for each child item to API

### ISSUE THREAD

**Issue by ThijsdejongSNC** [Paazl/magento2-checkout-widget#75]
This happens in Paazl\CheckoutWidget\Model\Api\Builder\Order::getProducts() and Paazl\CheckoutWidget\Model\Handler:Item

Paazl\CheckoutWidget\Model\Handler\Item::getPriceValue uses the quote item parent's (bundle) total value . Paazl\CheckoutWidget\Model\Api\Builder\Order::getProducts()  requests this for each child in the bundle.

The consequence of this is that one of our (non eu) customers that ordered a 500 euro bundle with 5 products now got a customs invoice for vat and duties on 2500,- worth of products.

Reproduce by creating a order with bundle for a non-eu country. Check the items in the Paazl backend or check $result on line 177 of Paazl\CheckoutWidget\Model\Api\Builder\Order.

**Comment by Frank-Magmodules** [comment]
HI @ThijsdejongSNC , sorry for the late response on this but we've fixed this in an earlier release (version [1.9.2](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.9.2).).  
Thank you for your patience and contribution to this. We are closing this issue now but please feel free to reopen the issue if this still occurs.
