### ISSUE TITLE
Modifying a order with customs invoice causes products to be added again

### ISSUE THREAD

**Issue by ThijsdejongSNC** [Paazl/magento2-checkout-widget#82]
Steps to reproduce:
- add product to cart
- choose a non-eu desitination
- create order
- push to paazl (see M2 backend, resend button)
- verify order has parcel content of N products in the cart
- Adjust ship address in M2 backend
- Push order to paazl again (resend button)
-  Verify in paazl backend that number the order has been added to the paazlOrder twice

**Comment by Frank-Magmodules** [comment]
HI @ThijsdejongSNC ,

We are happy to share that we've just released the new [1.9.3 version](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.9.3) with a fix for this issue.
Thank you again for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
