### ISSUE TITLE
Customers quote tokens again invalid after 30 days

### ISSUE THREAD

**Issue by peterjaap** [Paazl/magento2-checkout-widget#83]
See issue #14 - this was added in version 1.1.0.

However, in [this commit](https://github.com/Paazl/magento2-checkout-widget/commit/47b450986b319cf736a2fea289ee6ef656dd812a#diff-2de975e948a6337621847ecd57a5435e084eaf65efbcd25bd1626a4dccdc66ca) in version 1.2.0, calling of this code has been (accidentally?) removed. 

It was still present in 1.1.4; https://github.com/Paazl/magento2-checkout-widget/blob/1.1.4/Model/TokenRetriever.php#L127

The function is still there; https://github.com/Paazl/magento2-checkout-widget/blob/fd6bc8e54c6a3502e018c944b269362cd169f0bd/Model/TokenRetriever.php#L171

But it is called nowhere. This causes tokens to not be refreshed, which will cause no shipping methods in the checkout for logged in customers that have carts that are older than 30 days.

**Comment by peterjaap** [comment]
After checking this on production, it looks like the tokens are refreshed. We were running into this on a staging server with an outdated database and no cron jobs running.

So it looks like there is a new mechanism introduced at a certain point to refresh the tokens, but the method `refreshQuoteReferenceApiToken` was left behind as an oversight and is now dead code.

**Comment by Marvin-Magmodules** [comment]
Hi @peterjaap,

Yes correct, looks like this function was left behind after refactor: https://github.com/Paazl/magento2-checkout-widget/blob/master/Model/TokenRetriever.php#L171

The logic for refreshing the token was moved to https://github.com/Paazl/magento2-checkout-widget/blob/master/Model/TokenRetriever.php#L127-L133

Will open internal issue to remove the dead code.

**Comment by peterjaap** [comment]
Great!
