### ISSUE TITLE
Currency symbol always show EUR despite using a different currency

### ISSUE THREAD

**Issue by trebb0r** [Paazl/magento2-checkout-widget#9]
Hello,

Currently the currency symbol on the shipping method costs always using euro even when you have set a different currency.

I made a pull request that has this fixed. Can you take a look at it?

Greetings,

Robbert

**Comment by Marvin-Magmodules** [comment]
Hi @trebb0r, thank you for issue report and PR. Just merged this into the master and created a new release, see [v1.0.7](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.0.7). Closing this issue now, but feel free to reopen is the issues still occurs
