### ISSUE TITLE
fatal error if shipping method is not set on order.

### ISSUE THREAD

**Issue by muuk-isaac** [Paazl/magento2-checkout-widget#90]
In `Paazl\CheckoutWidget\Helper\Order::isPaazlOrder()` there is no check if the Shipping Method is set on the order. when passing null to `Paazl\CheckoutWidget\Helper\Order:: isPaazlShippingMethod()` you will get a fatal error. 

please add a is_string check and throw a proper exception

**Comment by Marvin-Magmodules** [comment]
HI @muuk-isaac,

We are happy to share that we've just released the new [1.11.2 version](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.11.2) with a fix for this issue. Thank you again for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
